version: "3.3"

services:
  development:
    container_name: repository_name_dev
    image: localhost/repository_name:tag
    working_dir: /root/repository_name/src
    network_mode: "host"
    privileged: true
    stdin_open: true
    security_opt:
      - seccomp:unconfined
    cap_add:
      - ALL
    environment:
      DISPLAY: $DISPLAY
      ROS_LOCALHOST_ONLY: 1
    volumes:
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - /etc/ssl/certs:/etc/ssl/certs