version: "3.3"

services:
  development:
    container_name: sc2079_development
    image: sc2079_dev:latest
    working_dir: /root/sc2079
    network_mode: "host"
    privileged: true
    stdin_open: true
    ipc: host
    devices:
      - /dev:/dev
    security_opt:
      - seccomp:unconfined
    cap_add:
      - ALL
    environment:
      DISPLAY: $DISPLAY
    volumes:
      # - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      # - /etc/ssl/certs:/etc/ssl/certs
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/etc/.gitconfig
      - .:/root/sc2079/
